### ISSUE TITLE
Перевести калькулятор в npm зависимость

### ISSUE THREAD

**Issue by olgapshen** [TechnoFractal/calculator#11]
Для подключения к плагину Droopal-а.
Вот связанная задача:
https://github.com/TechnoFractal/technofractal/issues/1

От каждого калькулятора, требуется функция которая будет привязывать к определенному div-у соответствующий калькулятор, на подобии плагинов выводящих календари.
Разработка будет вестись в новой ветке: calc-npm

**Comment by olgapshen** [comment]
Оставляем комментарии.
Кому вообще не понятно что надо делать?

**Comment by Lady3mlnm** [comment]
Неактуально. Закрываю.
