### ISSUE TITLE
Увеличить размер документов, допустимых к загрузке на главный сайт

### ISSUE THREAD

**Issue by Lady3mlnm** [TechnoFractal/calculator#3]
До 20 Мб. 
**Небольшое** _тестовое_ **_оформление_**.

**Comment by olgapshen** [comment]
https://www.a2hosting.com/kb/developer-corner/php/using-php.ini-directives/php-maximum-upload-file-size

Выставила - 
post_max_size: 21M
upload_max_filesize: 20M
