### ISSUE TITLE
Сайт: добавить капчу на комментарии

### ISSUE THREAD

**Issue by Lady3mlnm** [TechnoFractal/calculator#4]
Капча на комментарии для незарегестрированных пользователей. Я уже пыталась задействовать модуль "CAPTCHA" (v.beta1), но не удалось заставить его работать.

**Comment by L3M-2** [comment]
Решено. Необходимо было в настройках модуля CAPTCHA на вкладке CAPTCHA Point прописать новый пункт "comment_comment_form". :)

**Comment by olgapshen** [comment]
![image](https://user-images.githubusercontent.com/13800244/28282884-b3a425ea-6b34-11e7-9934-f051e8ebbf3c.png)
Ага )) вижу )) супер!!!
