### ISSUE TITLE
Сайт: настроить FTP-доступ на Drupal

### ISSUE THREAD

**Issue by Lady3mlnm** [TechnoFractal/calculator#7]
FTP-доступ для движка сайта. Он значительно облегчает установку новых модулей, тем, а также обновления существующих.

**Comment by olgapshen** [comment]
Скиньте мне доступы.

**Comment by olgapshen** [comment]
![image](https://user-images.githubusercontent.com/13800244/28281937-60b3dd6a-6b31-11e7-953d-dc9a9dc483f1.png)
Мне удалось установить плагины...
И у тебя есть FTP доступ.
Поясни - что и где надо конфигурировать...

**Comment by olgapshen** [comment]
![image](https://user-images.githubusercontent.com/13800244/28283251-e75567d6-6b35-11e7-9304-b844fb7f5eda.png)
Установила модуль для backup-а используя ссылку от сюда: https://www.drupal.org/project/backup_migrate
Просто прописала твой пользователь и пароль от FTP.
На надо бы сгенирировать более сложные пароли.
