### ISSUE TITLE
Сайт: удалить папку "drupal-8.3.5" в корне сайта

### ISSUE THREAD

**Issue by Lady3mlnm** [TechnoFractal/calculator#8]
Папка была создана скриптом автоматической распаковки архива. Распаковалось не туда, куда нужно. Права папки не позволяют стереть её напрямую из FileZilla, а также невозможно из FileZilla эти самые права изменить. В работе папка не мешает, однако занимает 50 Мб пространства.

**Comment by olgapshen** [comment]
Done.
